title: "Portfolio"
description: "Portfolio"
baseurl: ""
url: "https://just-in-pierce.github.io/just-in-pierce/"  # If hosting on GitHub Pages, you might set: "https://username.github.io/reponame"

# If you use GitHub Pages, add:
# remote_theme: jekyll/themes@vX.X  (optional)

# Exclude any folders you don't want processed:
exclude:
  - node_modules
  - vendor
